### PR TITLE
Update templates.jsx

### PR DESCRIPTION
**Pull request by minhoryang**

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
I took this from their own documentation site

https://docs.angularjs.org/guide/introduction

Going to stick with their phrasing

**Comment by minhoryang** [comment]
[That link](https://docs.angularjs.org/guide/introduction) was not for Angular2.
Angular2's homepage is https://angular.io/
So we need to change the whole lines for Angular2. (hmm..)

FYI, from Angular2, to future Angular4, 5, 6..., will be called as Angular.
["Ok... let me explain: it's going to be Angular 4.0, or just Angular"](http://angularjs.blogspot.com/2016/12/ok-let-me-explain-its-going-to-be.html)

**Comment by MarshallOfSound** [comment]
Hm, interesting 😄 Is there an equivilent block for angular 2 😃

**Comment by minhoryang** [comment]
I tried to find that block, but nothing catch my eyes.

Perhaps... `<meta name="description">` from https://angular.io/
```
Angular is a development platform for building mobile and desktop web applications.
```

or why don't we just use https://en.wikipedia.org/wiki/Angular_(application_platform) 's first line?
```
Angular (commonly referred to as "Angular 2+" or "Angular 2") is a TypeScript-based open-source front-end web application platform led by the Angular Team at Google and by a community of individuals and corporations to address all of the parts of the developer's workflow while building complex web applications. Angular is a complete rewrite from the same team that built AngularJS.
```

**Pull request closed without merging**
